spring.application.name=taskmanager
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always

# REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT
jwt.secret=${JWT_SECRET}

# Circuit Breaker
resilience4j.circuitbreaker.instances.taskService.sliding-window-size=10
resilience4j.circuitbreaker.instances.taskService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.taskService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.taskService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.taskService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.taskService.register-health-indicator=true
management.health.circuitbreakers.enabled=true