spring.application.name=taskmanager
spring.datasource.url=jdbc:tc:postgresql:16:///taskmanager
spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver
spring.jpa.hibernate.ddl-auto=create-drop
